# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'LearnLottieDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'lottie-ios'
  # Pods for LearnLottieDemo

  target 'LearnLottieDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LearnLottieDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
